### ISSUE TITLE
`>>` operator does not initalize trait with initial value

### ISSUE THREAD

**Issue by pberkes** [enthought/qt_binder#47]
In a `A >> B` expression, any change to A is pushed to B, but the initial value of A is not pushed to B.

In the following example, pushing the "print_something" button prints `something is "not default"` instead of the expected `something is "default"`

```
from qt_binder.api import Bound
from qt_binder.widgets import TextField

from traits.api import Button, HasStrictTraits, Unicode
from traitsui.api import View


class SomethingView(HasStrictTraits):

    print_something = Button

    def _print_something_fired(self):
        print 'something is "{}"'.format(self.something_value)

    something_value = Unicode('not default')

    def _something_value_changed(self):
        print 'something changed', self.something_value

    def default_traits_view(self):
        view = View(
            Bound(
                TextField(
                    value='default',
                    id='something'
                ),
                'something.value >> object.something_value',
            ),
            'print_something',
        )
        return view


if __name__ == '__main__':
    view = SomethingView()
    view.configure_traits()
```

**Comment by rkern** [comment]
This is as documented. `>>`/`PushedTo` is used often for `Event` traits, which have no value to initialize with.

A workaround is to use a `=`/`SetOnceTo` binding in addition to the `>>`/`PushedTo`.

**Comment by pberkes** [comment]
Thank you, makes sense.

**Comment by rkern** [comment]
Well, I lie. `<<`/`PulledFrom` is more frequently used with `Event` traits on the model, and it is coded to handle that case just fine when it performs the assignment on initialization. Rather, the typical problematic left-hand-side for `>>`/`PushedTo` is a `QtSignal` on a `Binder`. We could probably do the same kind of explicit check for `QtSignal` that we do with `Event` if this workaround becomes a common pattern. I don't _think_ it will be particularly common, because one is typically not interested in propagating the widget's state to the model until there is an actual user interaction. But let's keep an eye on our usage of that and revisit as needed.

**Comment by pberkes** [comment]
For the record, in this case we built a custom LineEdit that had a "valid" boolean trait that we wanted to listen to.
